### PR TITLE
py3

### PR DESCRIPTION
**Pull request by mcrowson**
got rid of base64 stuff
using six to get correct bytes type
serializing the whole object by desired type and not doing the json wrap if pickle. Keeps it simpler.

Double check my encoding stuff. Works for me but I hate it, so have little confidence in encoding/decoding crap

### CODE REVIEW

**Comment by Miserlou** [comment]
Why did you take out the B64 stuff? I think that was there for a reason.

**Comment by mcrowson** [comment]
It looks like it was there to make the pickled object Json-able, but I got rid of that. It only serialize a to one or the other.

**Comment by mcrowson** [comment]
What's the holdup here. got another project in py3 and want to use this.

**Comment by dudil** [comment]
Hi - 

Would love to see support for Python3.
Anyway I can help/assist?

Is this branch still active or there is a new one?

Thanks!

**Comment by Miserlou** [comment]
This PR changes the behavior quite a bit, I think. The point is that each object can be human-inspected from S3, so each "item" is a JSON object containing the serialized value. I think this is no longer the case?

**Comment by Miserlou** [comment]
I'd also like to be able to merge this at the same time: https://github.com/Miserlou/NoDB/pull/12

**Comment by dudil** [comment]
To be honest - initially, I just thought of putting id Python3 statements on serialization for minimal impact. something like: https://stackoverflow.com/questions/9079036/detect-python-version-at-runtime

Not elegant but should work. As the only issue was with serialization native JSON object in Py3

**Comment by mcrowson** [comment]
The reason I changed it was because the current approach encodes the default pickle 3 times. 

Object -> Pickle serial, Pickle serial -> base64, base64 -> json

It just felt super convoluted and I wasn't sure what value it adds aside from having the meta-data as human readable. If that is important, than we can add all that stuff back in to keep it. Just encoding and bytes and all that jazz from py2/3 was less straight forward. That's why it was just a little easier for me to just have the single encoding of pickle/json.

**Comment by dudil** [comment]
That makes sense but also not changing the whole project for a feature. That makes tracking and further bugfixing a bad headache. I'm just want to use it Py3 with straight JSON objects...
So guys - is it Ok I'll open a new branch just for this? or you feel it is not appropriate? I don't want to make a mess.
BTW - amazing project :)

**Comment by mcrowson** [comment]
Feel free to take it and run. If anything I have here is helpful use it.

**Comment by bendog** [comment]
Going to close this as Python 3 is now supported

**Pull request closed without merging**
