### PR TITLE
added all() method and some minor changes

### PR DESCRIPTION
**Pull request by kecabojan**
- added all() method to retrieve all S3 objects. I think there is no point in using cache folder in this case.
- moved 'bucket' to init method since it has to be set
- removed region class variable since it's not used anywhere
- added Moto lib to test_requirements for mocking boto3 api
- added/modified tests

### CODE REVIEW

**Comment by Miserlou** [comment]
Tests are still failing, can you fix that? You might also want to look at the `placebo` library for replaying those `boto` calls like we do in Zappa.

**Comment by antgel** [comment]
@kecabojan @Miserlou Any news on this? If it's not implemented soon, we'll have to move to another backend for our use case. :( If it could be made to work quickly, we would be happy to fund development.

**Comment by kecabojan** [comment]
Tests are (finally) fixed. It is up to @Miserlou to merge or not. Thanks.

**Comment by antgel** [comment]
@kecabojan Wow, thanks! I'll try cherry-picking it in the meantime. :)

**Review by bendog — APPROVED** [review]
this looks good to go

**Pull request merged**
